name: conda_environment
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.6.5
  - numpy
  - pandas
  - pytorch-cpu
  - scikit-image
  - simplejson
  - minio
  - requests
  - igor
  - pip
  - xlrd=1.2.0
  - python-slugify=5.0.2
  - defaults::libprotobuf=3.17.2
  - defaults::protobuf=3.17.2
  - x264=20131218
  - opencv=3.4.1
  - imutils=0.5.4