name: conda_environment
channels:
  - conda-forge
  - fastai
  - pytorch
dependencies:
  - python=3.6.5
  - fastai=1.0.57
  - pytorch=1.2.0
  - torchvision=0.4.0
  - cpuonly
  - simplejson
  - minio
  - requests
  - igor
