name: conda_environment
channels:
  - conda-forge
  - fastai
  - pytorch
dependencies:
  - python=3.7.10
  - fastai=1.0.57
  - pytorch=1.2.0
  - torchvision=0.4.0
  - xlrd=1.2.0
  - cpuonly
  - simplejson
  - minio
  - requests
  - igor
  - python-slugify=5.0.2
  - x264=20131218
  - opencv=3.4.1
  - imutils=0.5.4

