name: conda_environment
channels:
  - conda-forge
  - fastai
  - pytorch
dependencies:
  - python=3.6.5
  - fastai=1.0.52
  - cuda100
  - pytorch
  - torchvision
  - pytorch-nightly
  - simplejson
  - minio
  - requests
    # Data parsers
  - openpyxl=3.0.7
  - hyperspy-base=1.6.4
  - igor
  - xlrd=1.2.0