name: conda_environment
channels:
  - conda-forge
  - fastai
  - pytorch
dependencies:
  - python=3.6.5
  - fastai=1.0.52
  - cuda100
  - pytorch
  - torchvision
  - pytorch-nightly
  - simplejson
  - minio
  - requests
  - igor